/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Autenticacion;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;
import javax.swing.JPanel;
import Controlador.Autenticacion.ControladorPrincipalAdministrador;

public class GUIPrincipalAdmin extends javax.swing.JFrame {
    
    private String nombre;
    private ControladorPrincipalAdministrador controladorPrincipal;
    
    /**
     * Creates new form ventana
     */
    public GUIPrincipalAdmin(String nombre) {
        initComponents();
        controladorPrincipal = new ControladorPrincipalAdministrador(this, citas, Usuarios, empleados, pacientes,Pagos);
        this.nombre = nombre;
        setInfoEncabezado();
        Usuarios.addActionListener(controladorPrincipal);
        citas.addActionListener(controladorPrincipal);
        empleados.addActionListener(controladorPrincipal);
        pacientes.addActionListener(controladorPrincipal);
        Pagos.addActionListener(controladorPrincipal);
    }
    
    public void setContenido(JPanel contenido){
        content.removeAll();
        content.add(contenido, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    
    public void setInfoEncabezado() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Obtener la fecha y hora actual
                LocalDateTime fechaHoraActual = LocalDateTime.now();

                // Formatear la fecha y hora como cadenas
                DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                String fechaFormateada = fechaHoraActual.format(formatoFecha);

                DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("hh:mm:ss a");
                String horaFormateada = fechaHoraActual.format(formatoHora);

                // Actualizar las etiquetas con la fecha y hora actuales
                lblFecha.setText(fechaFormateada);
                lblHora.setText(horaFormateada);
            }
        });
        // Iniciar el temporizador
        timer.start();
        lblNombreUsuario.setText("Administrador: " + nombre);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        menuOpciones = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        citas = new javax.swing.JButton();
        Usuarios = new javax.swing.JButton();
        pacientes = new javax.swing.JButton();
        empleados = new javax.swing.JButton();
        Pagos = new javax.swing.JButton();
        encabezado = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1120, 570));
        setResizable(false);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuOpciones.setBackground(new java.awt.Color(11, 58, 131));
        menuOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1707068948215.png"))); // NOI18N
        lblLogo.setText("Sweet Tooth");
        menuOpciones.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 200, 80));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        menuOpciones.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 100, -1));

        citas.setBackground(new java.awt.Color(18, 91, 173));
        citas.setForeground(new java.awt.Color(255, 255, 255));
        citas.setText("Citas");
        citas.setBorder(null);
        citas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citasActionPerformed(evt);
            }
        });
        menuOpciones.add(citas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 230, 50));

        Usuarios.setBackground(new java.awt.Color(18, 91, 173));
        Usuarios.setForeground(new java.awt.Color(255, 255, 255));
        Usuarios.setText("Usuarios");
        Usuarios.setBorder(null);
        Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosActionPerformed(evt);
            }
        });
        menuOpciones.add(Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 230, 50));

        pacientes.setBackground(new java.awt.Color(18, 91, 173));
        pacientes.setForeground(new java.awt.Color(255, 255, 255));
        pacientes.setText("Pacientes");
        pacientes.setBorder(null);
        pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesActionPerformed(evt);
            }
        });
        menuOpciones.add(pacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 230, 50));

        empleados.setBackground(new java.awt.Color(18, 91, 173));
        empleados.setForeground(new java.awt.Color(255, 255, 255));
        empleados.setText("Empleados");
        empleados.setBorder(null);
        empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadosActionPerformed(evt);
            }
        });
        menuOpciones.add(empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 230, 50));

        Pagos.setBackground(new java.awt.Color(18, 91, 173));
        Pagos.setForeground(new java.awt.Color(255, 255, 255));
        Pagos.setText("Pagos");
        Pagos.setBorder(null);
        Pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagosActionPerformed(evt);
            }
        });
        menuOpciones.add(Pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 230, 50));

        fondo.add(menuOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 610));

        encabezado.setBackground(new java.awt.Color(25, 118, 209));

        lblFecha.setBackground(new java.awt.Color(255, 255, 255));
        lblFecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblHora.setBackground(new java.awt.Color(255, 255, 255));
        lblHora.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblNombreUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout encabezadoLayout = new javax.swing.GroupLayout(encabezado);
        encabezado.setLayout(encabezadoLayout);
        encabezadoLayout.setHorizontalGroup(
            encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, encabezadoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 394, Short.MAX_VALUE)
                .addGroup(encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        encabezadoLayout.setVerticalGroup(
            encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encabezadoLayout.createSequentialGroup()
                .addGroup(encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, encabezadoLayout.createSequentialGroup()
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 72, Short.MAX_VALUE))
        );

        fondo.add(encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 890, 130));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        scrollPane1.add(content);

        fondo.add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 890, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void citasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citasActionPerformed
        
    }//GEN-LAST:event_citasActionPerformed

    private void UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosActionPerformed
        
    }//GEN-LAST:event_UsuariosActionPerformed

    private void pacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacientesActionPerformed

    private void empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empleadosActionPerformed

    private void PagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PagosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pagos;
    private javax.swing.JButton Usuarios;
    private javax.swing.JButton citas;
    private javax.swing.JPanel content;
    private javax.swing.JButton empleados;
    private javax.swing.JPanel encabezado;
    private javax.swing.JPanel fondo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JPanel menuOpciones;
    private javax.swing.JButton pacientes;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
