/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Pacientes;

import Controlador.Pacientes.ControladorPacientes;
import java.awt.BorderLayout;
import javax.swing.JPanel;

public class GUIPacientes extends javax.swing.JFrame {

    private ControladorPacientes controladorPacientes;
    /**
     * Creates new form AgendarCita
     */
    public GUIPacientes() {
        initComponents();
        controladorPacientes = new ControladorPacientes(this, registrar, modificar, mostrar, eliminar);
        registrar.addActionListener(controladorPacientes);
        mostrar.addActionListener(controladorPacientes);
        eliminar.addActionListener(controladorPacientes);
        modificar.addActionListener(controladorPacientes);
        
    }
    
    public JPanel getContenido(){
        return Fondo;
    }
    
    public void setContenido(JPanel contenido){
        content.removeAll();
        content.add(contenido, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Fondo = new javax.swing.JPanel();
        mostrar = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        eliminar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mostrar.setBackground(new java.awt.Color(255, 255, 255));
        mostrar.setForeground(new java.awt.Color(18, 91, 173));
        mostrar.setText("Mostrar Informacion de paciente");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        Fondo.add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 250, 40));

        registrar.setBackground(new java.awt.Color(255, 255, 255));
        registrar.setForeground(new java.awt.Color(18, 91, 173));
        registrar.setText("Registrar paciente");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        Fondo.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        modificar.setBackground(new java.awt.Color(255, 255, 255));
        modificar.setForeground(new java.awt.Color(18, 91, 173));
        modificar.setText("Modificar paciente");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        Fondo.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 200, 40));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        Fondo.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 890, 480));

        eliminar.setBackground(new java.awt.Color(255, 255, 255));
        eliminar.setForeground(new java.awt.Color(18, 91, 173));
        eliminar.setText("Eliminar paciente");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        Fondo.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed

        
    }//GEN-LAST:event_registrarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed

    }//GEN-LAST:event_modificarActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed

    }//GEN-LAST:event_mostrarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed

    }//GEN-LAST:event_eliminarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel content;
    private javax.swing.JButton eliminar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton modificar;
    private javax.swing.JButton mostrar;
    private javax.swing.JButton registrar;
    // End of variables declaration//GEN-END:variables
}
